### PR TITLE
fix: output zero when displaying human results

### PR DESCRIPTION
**Pull request by leostewart**
### What does this PR do?

Outputs `0` instead of an empty string (regular or aggregate queries) or `null` (subqueries) in human result format.

### What issues does this PR fix or reference?

Attempts to fix https://github.com/forcedotcom/cli/issues/1892

### Notes

I didn't add additional tests as it might not be justified, but let me know otherwise.

### CODE REVIEW

**Comment by WillieRuemmele** [comment]
Hi @leostewart thanks for the contribution - sorry we missed it until now. Could you add a unit test verifying that a `0` is printed to make sure this won't break again in the future?

**Comment by leostewart** [comment]
Hi @WillieRuemmele, I've added a few unit tests for the mentioned scenarios. As this is a bit of an edge case, I wasn't sure how best to incorporate them into the existing tests, so feel free to make suggestions/changes.

**Comment by WillieRuemmele** [comment]
### QA Notes

setup:
`sfdx data record create -s Opportunity -v "Name=testOpportunity StageName=Prospecting CloseDate=2023-12-31 Amount=0"`

--- 
✅ : displaying 0
```
 ➜  sfdx data query -q "SELECT Name, Amount FROM Opportunity WHERE Name='testOpportunity'"
 NAME            AMOUNT 
 ─────────────── ────── 
 testOpportunity 0 
```
vs
```
 ➜  sfdx data query -q "SELECT Name, Amount FROM Opportunity WHERE Name='testOpportunity'"
 NAME            AMOUNT 
 ─────────────── ────── 
 testOpportunity        
Total number of records retrieved: 1.
```
✅ : UTs pass
✅ : NUTs pass
✅ : 0 in csv
✅ : null in csv
✅ : null in human
🏆 : fixes another bug with `false`
before:
```
 ➜  sfdx data query -q "SELECT Name, Amount,HasOverdueTask,Description,Id FROM Opportunity WHERE Name='testOpportunity'"       
 NAME            AMOUNT HASOVERDUETASK DESCRIPTION ID                 
 ─────────────── ────── ────────────── ─────────── ────────────────── 
 testOpportunity                       null        006DR00000HqjUGYAZ 
```

after:
```
 ➜  sfdx data query -q "SELECT Name, Amount,HasOverdueTask,Description,Id FROM Opportunity WHERE Name='testOpportunity'" 
 NAME            AMOUNT HASOVERDUETASK DESCRIPTION ID                 
 ─────────────── ────── ────────────── ─────────── ────────────────── 
 testOpportunity 0      false          null        006DR00000HqjUGYAZ 
```

**Comment by WillieRuemmele** [comment]
Thank you so much @leostewart 🎉 🏆

**Pull request merged**
